/**
 * The Terms & Privacy text the onboarding consent step shows, and the version
 * string persisted with the user's acceptance (`settings.acceptedTermsVersion`).
 *
 * Shipped IN the app, not fetched: consent is a launch blocker, so it must be
 * readable with no network and no dead link. There is no /terms or /privacy
 * page on insertgo.ai yet — when there is, link to it from here rather than
 * replacing this text (the user agreed to *this* wording at this version).
 *
 * Bump `LEGAL_VERSION` on any substantive edit. Anyone whose stored
 * `acceptedTermsVersion` differs is re-asked (see `needsConsent`).
 */

/** Version pinned into settings when the user accepts. Semver: bump minor+
 *  for substantive changes, patch for typo fixes that don't change meaning. */
export const LEGAL_VERSION = "1.0.0";

/** Consent checkbox label. Single source — the store's gate, the UI's label
 *  and the test all read this constant, so the version can never drift
 *  between what was shown and what was recorded. */
export const CONSENT_LABEL =
  `I accept the Terms & Conditions and Privacy Policy v${LEGAL_VERSION}`;

/** True when the user has not accepted the currently shipped version. */
export function needsConsent(acceptedVersion: string | null): boolean {
  return acceptedVersion !== LEGAL_VERSION;
}

export type LegalDocument = {
  id: "terms" | "privacy";
  title: string;
  /** Section heading + body paragraphs, rendered into a scrollable region. */
  sections: Array<{ heading: string; body: string }>;
};

export const TERMS: LegalDocument = {
  id: "terms",
  title: "Terms & Conditions",
  sections: [
    {
      heading: "1. What InsertGo is",
      body:
        "InsertGo is a Windows desktop application that improves prompts you " +
        "are drafting for AI assistants. It reads the text field you are " +
        "typing in when you press its hotkey, sends that text to an AI model " +
        "for rewriting, and writes the improved text back into the same " +
        "field. It never presses Enter or submits anything on your behalf.",
    },
    {
      heading: "2. The licence you get",
      body:
        "You get a personal, non-exclusive, non-transferable licence to " +
        "install and use InsertGo on machines you control. You may not " +
        "resell, sublicense, or redistribute the application, and you may " +
        "not remove or circumvent its licensing checks.",
    },
    {
      heading: "3. AI output is not guaranteed",
      body:
        "Prompt improvement is generated by a language model. Output can be " +
        "wrong, incomplete, or unsuitable for your purpose, and InsertGo " +
        "makes no warranty about it. You are responsible for reviewing what " +
        "is written back into your field before you send it anywhere. " +
        "InsertGo replaces the whole content of the field it read — the " +
        "undo hotkey restores the previous text.",
    },
    {
      heading: "4. Your AI provider account",
      body:
        "When you bring your own API key, your prompts go directly from this " +
        "device to that provider under your own agreement with them, and " +
        "their terms, pricing, and rate limits apply to those requests. " +
        "InsertGo is not a party to that relationship and cannot refund " +
        "provider charges.",
    },
    {
      heading: "5. Acceptable use",
      body:
        "Do not use InsertGo to produce unlawful content, to impersonate " +
        "another person, or to process data you have no right to process. " +
        "Do not use it to capture text from applications belonging to other " +
        "people without their knowledge.",
    },
    {
      heading: "6. Payment, trials and refunds",
      body:
        "Paid plans and lifetime licences are billed through our payment " +
        "processor. Trials end automatically and do not convert to a paid " +
        "plan without an explicit purchase. Refund eligibility is stated at " +
        "the point of purchase.",
    },
    {
      heading: "7. Liability",
      body:
        "InsertGo is provided as-is to the fullest extent permitted by law. " +
        "We are not liable for lost work, lost data, or indirect or " +
        "consequential damages arising from use of the application. Nothing " +
        "here limits liability that cannot be limited by law.",
    },
    {
      heading: "8. Changes and termination",
      body:
        "These terms may be revised; a substantive revision raises the " +
        "version number and you will be asked to accept the new version " +
        "inside the app. You may stop using InsertGo and uninstall it at any " +
        "time, which removes its local data from this device.",
    },
  ],
};

export const PRIVACY: LegalDocument = {
  id: "privacy",
  title: "Privacy Policy",
  sections: [
    {
      heading: "What stays on this device",
      body:
        "Your prompts, prompt library, local history, settings, and skills " +
        "are stored on this PC only. API keys are stored in Windows " +
        "Credential Manager — never in a settings file, never in a log, and " +
        "never transmitted to InsertGo. Nothing you type is written to the " +
        "application log; logs record error conditions, not content.",
    },
    {
      heading: "What is read, and when",
      body:
        "InsertGo reads the contents of the focused text field only at the " +
        "moment you press its hotkey, and reads the current selection only " +
        "when the selection skill bar is enabled. Both use the Windows " +
        "accessibility API and are scoped to the applications on your " +
        "allowlist. Password fields are always refused: their text is never " +
        "read into memory, so it can never be sent anywhere.",
    },
    {
      heading: "Where your text goes",
      body:
        "Text you improve is sent to one AI provider so it can be rewritten. " +
        "With your own API key, it goes from this device straight to that " +
        "provider and InsertGo's servers never see it. On the managed plan, " +
        "it passes through InsertGo's relay to the model provider; relayed " +
        "text is not stored after the request completes and is not used to " +
        "train models.",
    },
    {
      heading: "Clipboard handling",
      body:
        "When the accessibility API cannot read a field, InsertGo falls back " +
        "to the clipboard: it saves your existing clipboard contents, uses " +
        "the clipboard to move text, then restores what was there before. " +
        "Your clipboard is never read at any other time.",
    },
    {
      heading: "Account and licensing data",
      body:
        "If you sign in, we process your email address, subscription state, " +
        "and a hardware identifier derived from this machine, in order to " +
        "operate your account and bind a lifetime licence to a device. We do " +
        "not sell personal data.",
    },
    {
      heading: "Your choices",
      body:
        "The selection skill bar can be switched off entirely, and the list " +
        "of applications InsertGo may read from is yours to edit in " +
        "Settings. Password managers and credential prompts are blocked by " +
        "default and cannot be read even if you widen the scope. " +
        "Uninstalling removes local data; your stored API keys can be " +
        "deleted from the Provider Keys page at any time.",
    },
  ],
};

export const LEGAL_DOCUMENTS: readonly LegalDocument[] = [TERMS, PRIVACY];
