<!-- GENERATED by ../Insert-Go Windows/scripts/sync-context.mjs. Do not edit by hand. -->
# InsertGo website — agent context

Next.js App Router website and managed API for InsertGo desktop.

## Sources of truth

- package.json: framework versions and npm scripts.
- INTEGRATION.md: authoritative Website/Desktop connection contract.
- DEV_SETUP.md: local Better Auth, PostgreSQL, OAuth, and desktop PKCE setup.
- Sibling Insert-Go Windows/SPEC.md: authoritative product behavior and desktop contracts.
- This file is generated; change ../Insert-Go Windows/scripts/sync-context.mjs instead.

## Generated stack

- Next.js ^15.3.8 using App Router
- React ^19.0.0; React DOM ^19.0.0
- Tailwind CSS ^4.1.0
- Better Auth ^1.6.23; SSO ^1.6.23
- PostgreSQL via pg ^8.22.0
- TypeScript ^5.7.0; tests use Vitest ^4.1.10
- Framer Motion ^11.15.0

## Architecture and control flow

- app: Next.js pages, layouts, route handlers, desktop authorization UI.
- app/api/auth: Better Auth handler.
- app/api/desktop/authorize and app/api/desktop/token: Authorization Code + PKCE exchange for public desktop client.
- app/api/ai/generate: authenticated managed AI relay.
- app/api/billing: checkout and webhook routes.
- lib/auth.ts: Better Auth configuration, OTP/OAuth/SSO, bearer sessions, entitlement enrichment.
- lib/desktopAuth.ts: PKCE validation, short-lived single-use authorization codes, fixed insertgo:// callback.
- lib/db.ts and PostgreSQL helpers: server-only persistence.
- components: shared marketing and application UI.

## Authentication invariants

- BETTER_AUTH_URL and desktop VITE_API_URL must use identical origin.
- Desktop callback carries authorization code, never session token.
- Require S256 PKCE; authorization codes stay short-lived and single-use.
- Validate all route input and keep constant-time verifier comparison.
- Never expose secrets to client bundles or logs.
- Use DEV_SETUP.md for schema, environment, OAuth redirect, and local OTP steps.

## Commands

- npm run dev — Next.js development server
- npm run build — production build
- npm test — Vitest once
- npm run test:watch — Vitest watch mode

## Working rules

- Keep server-only code and secrets out of client components.
- Preserve App Router conventions and existing route/service boundaries.
- Validate request bodies, authorization, redirect targets, and webhook input.
- Add focused tests beside existing auth, billing, DB, and utility tests.
- Do not weaken security headers or PKCE/auth checks without explicit review.
