import React from "react";
import { AbsoluteFill, OffthreadVideo, staticFile, useCurrentFrame } from "remotion";
import { T } from "./tokens";
import { clamp } from "./ui";

/**
 * A Veo plate as scene environment.
 *
 * Plates are generated by scripts/render-plates.mjs from scripts/veo-plates.json
 * and are ENVIRONMENT ONLY — no UI, no text, no product. Real InsertGo UI
 * composites on top inside remotion/scenes/*. Never put copy in a plate.
 *
 * Three things every scene needs from this component:
 *
 * 1. WINDOW ALIGNMENT. Plates are 8s at 24fps; scenes are 5s at 30fps. `startAt`
 *    picks which second of the plate the scene sits on, in PLATE seconds, so a
 *    scene can land its UI beat on the plate's own light beat (the skillbar
 *    cascade, the halo bloom) instead of fighting it.
 * 2. CONTRAST. Raw plates are far too bright behind body copy. `scrim` lays the
 *    canvas colour back over the footage; captions stay legible at 0.55+.
 * 3. PALETTE. Veo was directed cyan + violet (veo-plates.json), the product is
 *    cobalt-only. GRADE is the one knob for reconciling that; see below.
 */

// Ships ungraded, on purpose. Two grades were tried and both cost more than the
// palette mismatch does:
//   "hue-rotate(-50deg)"  — lands violet near cobalt, but cyan rotates to GREEN,
//                           which is the one hue the brand has no place for.
//   feColorMatrix R*0.45  — violet to blue with cyan intact, but every white
//                           hairline specular picks up a cyan cast.
// The UI composited on top is cobalt and separates from the plate on its own, so
// the plate stays exactly as generated. Re-grade in the plate prompts instead.
const GRADE = "none";

export const PLATE_FPS = 24;

type PlateProps = {
  /** plate id from veo-plates.json, e.g. "hero-glass" */
  id: string;
  /** where in the plate (seconds) this scene starts */
  startAt?: number;
  /** 0..1 how hard the canvas colour is laid back over the footage */
  scrim?: number;
  /**
   * css object-position. Only bites when `zoom` > 1: plates and compositions
   * are both 16:9, so object-fit cover has no overflow to shift otherwise.
   */
  objectPosition?: string;
  /** extra zoom on top of cover, for tightening a loose frame */
  zoom?: number;
  /** frames over which the plate fades up from black at scene start */
  fadeIn?: number;
};

export const Plate: React.FC<PlateProps> = ({
  id,
  startAt = 0,
  scrim = 0.55,
  objectPosition = "center",
  zoom = 1,
  fadeIn = 12,
}) => {
  const frame = useCurrentFrame();
  const up = clamp(frame, [0, fadeIn], [0, 1]);

  return (
    <AbsoluteFill style={{ background: T.bg }}>
      <AbsoluteFill style={{ opacity: up, filter: GRADE, transform: `scale(${zoom})` }}>
        <OffthreadVideo
          src={staticFile(`plates/${id}.mp4`)}
          startFrom={Math.round(startAt * PLATE_FPS)}
          muted
          style={{ width: "100%", height: "100%", objectFit: "cover", objectPosition }}
        />
      </AbsoluteFill>

      {/* flat scrim for overall level, plus a vignette so the frame edges fall
          back to canvas and the UI in the middle reads as the brightest thing */}
      <AbsoluteFill style={{ background: T.bg, opacity: scrim }} />
      <AbsoluteFill
        style={{
          background: `radial-gradient(120% 90% at 50% 45%, transparent 25%, ${T.bg} 100%)`,
          opacity: 0.85,
        }}
      />
    </AbsoluteFill>
  );
};

/** Scene shell for plate-backed scenes: plate behind, UI in front. */
export const PlateScene: React.FC<{ plate: PlateProps; children: React.ReactNode }> = ({
  plate,
  children,
}) => (
  <AbsoluteFill style={{ fontFamily: T.fontSans, color: T.ink }}>
    <Plate {...plate} />
    {children}
  </AbsoluteFill>
);
