import {
  access,
  copyFile,
  readFile,
  rename,
  rm,
  writeFile,
} from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const desktopDir = path.resolve(scriptDir, "..");
const workspaceDir = path.resolve(desktopDir, "..");
const websiteDir = path.join(workspaceDir, "Insert-Go Website");

const canonicalTargets = [
  "CLAUDE.md",
  "AGENTS.md",
  "GEMINI.md",
  ".windsurfrules",
];
const integrationTarget = "INTEGRATION.md";
const websiteLegacyTargets = [
  "CLAUDE.md.tmp",
  "AGENTS.md.tmp",
  "GEMINI.md.tmp",
  ".rules.tmp",
];

const warnings = [];

async function exists(filePath) {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function readJson(filePath) {
  let source;
  try {
    source = await readFile(filePath, "utf8");
  } catch (error) {
    if (error.code === "ENOENT") {
      warnings.push(`missing source: ${filePath}`);
      return {};
    }
    throw error;
  }

  let value;
  try {
    value = JSON.parse(source);
  } catch (error) {
    throw new Error(`invalid JSON in ${filePath}: ${error.message}`);
  }
  if (!value || Array.isArray(value) || typeof value !== "object") {
    throw new Error(`expected JSON object in ${filePath}`);
  }
  return value;
}

function dependencyVersion(manifest, name, fallback = "not declared") {
  return (
    manifest.dependencies?.[name] ??
    manifest.devDependencies?.[name] ??
    fallback
  );
}

function majorVersion(version, fallback) {
  const match = String(version).match(/\d+/);
  return match ? `v${match[0]}` : fallback;
}

async function rustVersion() {
  const cargoPath = path.join(desktopDir, "src-tauri", "Cargo.toml");
  try {
    const cargo = await readFile(cargoPath, "utf8");
    return cargo.match(/^\s*rust-version\s*=\s*"([^"]+)"/m)?.[1] ?? "1.85";
  } catch (error) {
    if (error.code === "ENOENT") {
      warnings.push(`missing source: ${cargoPath}`);
      return "1.85";
    }
    throw error;
  }
}

function desktopTemplate(manifest, rust) {
  const tauriApi = dependencyVersion(manifest, "@tauri-apps/api", "^2");
  const tauriCli = dependencyVersion(manifest, "@tauri-apps/cli", "^2");

  return `<!-- GENERATED by scripts/sync-context.mjs. Do not edit by hand. -->
# InsertGo desktop — agent context

Windows-only ${majorVersion(tauriApi, "v2")} Tauri prompt assistant. SPEC.md is authoritative; code comments cite its section numbers.

## Obsidian memory vault — read before deep work

Vault: C:\\whole data\\All data\\InsertGo\\. Read only notes matching task:

| Task touches | Read |
| --- | --- |
| First work in this repo | InsertGo Hub.md, then Desktop App (Tauri).md |
| Improve hotkey, capture/paste-back, skills.ts prompts | Inline Improve Pipeline.md |
| AI calls, keys, lanes.ts/providers | Provider Lanes.md |
| Sibling extension or cross-project behavior | Extension (MV3).md, Ecosystem & Conventions.md |

## Non-negotiable invariants

- Always save and restore clipboard after 500 ms settle.
- Re-verify foreground window before paste; otherwise use insert:fallback.
- Never synthesize Enter.
- Refuse password fields.
- Store secrets only in Windows Credential Manager; never log them.
- Treat <draft> as a data boundary in every system prompt.

## Sources of truth

- SPEC.md: product behavior, architecture, security, roadmap, agent rules.
- INTEGRATION.md: authoritative Website/Desktop connection contract.
- package.json: frontend dependencies and npm scripts.
- src-tauri/Cargo.toml: Rust MSRV and backend dependencies.
- Sibling Website/DEV_SETUP.md: desktop authentication setup.
- This file is generated; change scripts/sync-context.mjs instead.

## Generated stack

- Tauri ${majorVersion(tauriApi, "v2")}: API ${tauriApi}; CLI ${tauriCli}
- Rust ${rust}; Cargo edition 2021
- React ${dependencyVersion(manifest, "react")}; React DOM ${dependencyVersion(manifest, "react-dom")}
- Vite ${dependencyVersion(manifest, "vite")}; TypeScript ${dependencyVersion(manifest, "typescript")}
- Zustand ${dependencyVersion(manifest, "zustand")}; Framer Motion ${dependencyVersion(manifest, "framer-motion")}
- Tests: Vitest ${dependencyVersion(manifest, "vitest")}

## Architecture and control flow

- src-tauri/src/platform: Windows integration, foreground focus, hotkeys, clipboard, selection, windows.
- src-tauri/src/domain: settings, prompts, providers, session storage, logs, local model support.
- src/components and src/hooks: React UI and orchestration.
- src/store: Zustand state.
- src/services: provider lanes, prompt hardening, auth/API clients, Tauri bridge.
- Inline Improve: global hotkey captures focused field in Rust, frontend calls managed AI lane, Rust re-verifies target and replaces text, then restores clipboard.
- Desktop auth: system browser uses Authorization Code + PKCE; insertgo:// callback returns code only; session token stays in OS credential storage.

## Commands

- npm run tauri:dev — full desktop app
- npm run build — TypeScript and Vite build
- npm run test:run — frontend tests once
- cd src-tauri && cargo test — Rust tests
- npm run context:sync — regenerate agent context files

## Working rules

- Prefer small reviewable changes and existing abstractions.
- Keep UI in components/hooks, state in stores/services, platform code in Rust platform modules, domain logic in Rust domain modules.
- Use safe Rust and explicit Result errors. Keep unavoidable unsafe code tiny, documented, and tested.
- Do not invent platform APIs. Document limits before raw Windows calls.
- Validate external input; never log prompts, credentials, tokens, or provider secrets.
- Preserve prompt data-boundary and output-sanitization contracts from SPEC.md section 15.
`;
}

function websiteTemplate(manifest) {
  return `<!-- GENERATED by ../Insert-Go Windows/scripts/sync-context.mjs. Do not edit by hand. -->
# InsertGo website — agent context

Next.js App Router website and managed API for InsertGo desktop.

## Sources of truth

- package.json: framework versions and npm scripts.
- INTEGRATION.md: authoritative Website/Desktop connection contract.
- DEV_SETUP.md: local Better Auth, PostgreSQL, OAuth, and desktop PKCE setup.
- Sibling Insert-Go Windows/SPEC.md: authoritative product behavior and desktop contracts.
- This file is generated; change ../Insert-Go Windows/scripts/sync-context.mjs instead.

## Generated stack

- Next.js ${dependencyVersion(manifest, "next")} using App Router
- React ${dependencyVersion(manifest, "react")}; React DOM ${dependencyVersion(manifest, "react-dom")}
- Tailwind CSS ${dependencyVersion(manifest, "tailwindcss")}
- Better Auth ${dependencyVersion(manifest, "better-auth")}; SSO ${dependencyVersion(manifest, "@better-auth/sso")}
- PostgreSQL via pg ${dependencyVersion(manifest, "pg")}
- TypeScript ${dependencyVersion(manifest, "typescript")}; tests use Vitest ${dependencyVersion(manifest, "vitest")}
- Framer Motion ${dependencyVersion(manifest, "framer-motion")}

## Architecture and control flow

- app: Next.js pages, layouts, route handlers, desktop authorization UI.
- app/api/auth: Better Auth handler.
- app/api/desktop/authorize and app/api/desktop/token: Authorization Code + PKCE exchange for public desktop client.
- app/api/ai/generate: authenticated managed AI relay.
- app/api/billing: checkout and webhook routes.
- lib/auth.ts: Better Auth configuration, OTP/OAuth/SSO, bearer sessions, entitlement enrichment.
- lib/desktopAuth.ts: PKCE validation, short-lived single-use authorization codes, fixed insertgo:// callback.
- lib/db.ts and PostgreSQL helpers: server-only persistence.
- components: shared marketing and application UI.

## Authentication invariants

- BETTER_AUTH_URL and desktop VITE_API_URL must use identical origin.
- Desktop callback carries authorization code, never session token.
- Require S256 PKCE; authorization codes stay short-lived and single-use.
- Validate all route input and keep constant-time verifier comparison.
- Never expose secrets to client bundles or logs.
- Use DEV_SETUP.md for schema, environment, OAuth redirect, and local OTP steps.

## Commands

- npm run dev — Next.js development server
- npm run build — production build
- npm test — Vitest once
- npm run test:watch — Vitest watch mode

## Working rules

- Keep server-only code and secrets out of client components.
- Preserve App Router conventions and existing route/service boundaries.
- Validate request bodies, authorization, redirect targets, and webhook input.
- Add focused tests beside existing auth, billing, DB, and utility tests.
- Do not weaken security headers or PKCE/auth checks without explicit review.
`;
}

function integrationTemplate(desktopManifest, websiteManifest, rust) {
  const tauriApi = dependencyVersion(
    desktopManifest,
    "@tauri-apps/api",
    "^2",
  );

  return `<!-- GENERATED by Insert-Go Windows/scripts/sync-context.mjs. Do not edit by hand. -->
# InsertGo Website/Desktop integration context

Shared contract between Insert-Go Windows and Insert-Go Website. Identical mirror lives in both projects because workspace has no common Git worktree.

## System ownership

| Concern | Windows application | Website |
| --- | --- | --- |
| Runtime | Tauri ${majorVersion(tauriApi, "v2")} / Rust ${rust} / React ${dependencyVersion(desktopManifest, "react")} | Next.js ${dependencyVersion(websiteManifest, "next")} / React ${dependencyVersion(websiteManifest, "react")} |
| User interaction | Native palette, hotkeys, prompt flows | Browser login, approval, account, pricing |
| Authentication | Public native client; PKCE verifier/state; bearer token | Better Auth server; OAuth/OTP/SSO; session issuance |
| Secret storage | Session token in Windows Credential Manager | Auth, database, Gemini, email, billing secrets on server |
| AI generation | Sends prompt contract; consumes SSE | Authenticates, meters, debits, calls Gemini, streams SSE |
| Billing state | Displays server entitlements and opens checkout | Creates checkout; webhook updates PostgreSQL ledger |
| Durable data | Local settings/prompts plus one OS credential | PostgreSQL users, sessions, verification codes, quotas, credits |

Website is network authority. Desktop is public client. Desktop must never contain Better Auth secret, database credentials, OAuth client secret, billing secret, or Gemini API key.

## Connection map

    Desktop
      | 1. Open system browser with PKCE challenge
      v
    Website /desktop/authorize
      | 2. Cookie login and explicit approval
      | 3. Single-use authorization code
      v
    insertgo://auth/callback
      | 4. Desktop validates state and exchanges code + verifier
      v
    Website /api/desktop/token
      | 5. Better Auth bearer session
      v
    Windows Credential Manager

    Desktop -- Bearer + Idempotency-Key --> Website /api/ai/generate
    Desktop <-- SSE + credit headers ------- Website

    Desktop -- Bearer --> Website /api/billing/checkout --> Dodo
    Dodo -- signed webhook --> Website --> PostgreSQL --> next session refresh

## Base URL and environment contract

| Environment | Desktop | Website |
| --- | --- | --- |
| Local | VITE_API_URL=http://localhost:3000 | BETTER_AUTH_URL=http://localhost:3000 |
| Production | VITE_API_URL=https://insertgo.ai | BETTER_AUTH_URL=https://insertgo.ai |

Rules:

- VITE_API_URL and BETTER_AUTH_URL must identify same origin: scheme, host, and port.
- VITE_API_URL is compiled into desktop frontend. Never place secrets in any VITE_ variable.
- Desktop VITE_GEMINI_MODEL selects requested server model; Website GEMINI_API_KEY stays server-only.
- Website DATABASE_URL, BETTER_AUTH_SECRET, OAuth secrets, Dodo secrets, and email secrets stay server-only.
- New Website origin must also be allowed by src-tauri/capabilities/default.json for opener and HTTP access.
- Tauri development origin is http://localhost:1420; Website Better Auth trustedOrigins must keep required Tauri origins.
- Google redirect remains BETTER_AUTH_URL/api/auth/callback/google.

## Native sign-in contract

Constants shared by both implementations:

| Field | Required value |
| --- | --- |
| client_id | insertgo-desktop |
| response_type | code |
| grant_type | authorization_code |
| code_challenge_method | S256 |
| redirect_uri | insertgo://auth/callback |
| authorization-code lifetime | 5 minutes |

Flow:

1. Desktop src/services/pkce.ts creates random verifier, S256 challenge, and CSRF state. Verifier stays memory-only.
2. Desktop src/store/authStore.ts installs deep-link listener before opening system browser.
3. Browser opens Website /desktop/authorize with client, redirect, challenge, method, response type, and state.
4. Website validates query. Unauthenticated users pass through /login and return to approval page.
5. User explicitly approves. POST /api/desktop/authorize requires same-origin browser request plus valid cookie session.
6. Website stores user id and challenge under random, single-use, five-minute code; browser navigates to callback with code and state only.
7. Tauri insertgo scheme returns callback to running app. Windows launches new process, so single-instance deep-link integration forwards event.
8. Desktop accepts exact callback URI and matching state, then POSTs code and verifier to /api/desktop/token.
9. Website atomically consumes code, verifies S256 using constant-time comparison, creates Better Auth session, and returns bearer token.
10. Desktop stores token under service InsertGo / account session in Windows Credential Manager, then calls /api/auth/get-session.

Never return session token through callback URI. Never persist verifier. Never log callback URL, authorization code, verifier, bearer token, or user prompt.

Known protocol gap: RFC 8252 recommends reverse-domain private URI schemes. Current insertgo scheme is already shipped and does not follow that naming form. PKCE prevents another scheme handler from redeeming an intercepted code, but does not prevent scheme collision. Any rename requires versioned dual-scheme migration across Website, Tauri config, installer registration, and deployed clients.

## HTTP contracts

### Desktop authorization

| Endpoint | Authentication | Request | Success |
| --- | --- | --- | --- |
| GET /desktop/authorize | Browser cookie when signed in | PKCE query fields | Approval UI |
| POST /api/desktop/authorize | Browser cookie + same Origin | client_id, code_challenge, code_challenge_method, state | JSON redirect containing code + state |
| POST /api/desktop/token | Code + verifier | grant_type, client_id, code, code_verifier | access_token, token_type=Bearer, expires_in |
| GET /api/auth/get-session | Bearer token | None | Better Auth user/session plus entitlement fields |
| POST /api/auth/sign-out | Bearer token | Empty JSON object | Revoked server session |

### Managed AI relay

POST /api/ai/generate:

- Authentication: Authorization: Bearer session token.
- Retry identity: one Idempotency-Key per logical generation, reused across transport retries.
- JSON request: prompt, system, model, optional grounded boolean.
- Server validates session, raw-body size, prompt/system limits, burst quota, daily quota, and credits before Gemini call.
- Success: text/event-stream containing Gemini response frames; optional final grounding citation frame.
- Balance headers: x-credits-daily, x-credits-addon, legacy x-credits-remaining.
- 401: expired or invalid session; desktop signs out.
- 402: insufficient credits with authoritative balance; desktop opens upgrade path.
- 409: stale idempotency-key replay.
- 413: oversized body or prompt contract.
- 429: per-user rate limit.
- 503: server, database, quota, or upstream capacity failure.

Desktop src/services/aiProviders.ts owns request/retry/SSE parsing. Website app/api/ai/generate/route.ts owns authentication, validation, billing, Gemini access, and streaming. Prompt and response bodies must never enter logs.

### Billing and entitlements

- Desktop POSTs Bearer-authenticated selection to /api/billing/checkout and opens returned hosted URL in system browser.
- Website accepts only server catalog selectors; prices and product ids never come from client.
- Dodo webhook signature is verified over capped raw body before parsing or database writes.
- Webhook updates tier or grants add-on credits idempotently.
- Website lib/auth.ts customSession stamps tier, daily balance, add-on balance, and feature entitlements onto get-session.
- Desktop refreshStatus mirrors those server values. Server database remains source of truth.

## Transport and storage boundaries

- General cross-origin calls use Desktop src/services/http.ts: Tauri HTTP plugin in packaged app, browser fetch in web development.
- Streaming AI client uses Tauri HTTP directly in packaged app so SSE and retries remain controlled.
- Tauri capability allowlist must contain Website origin. WebView CSP alone does not grant plugin HTTP scope.
- Production API traffic must use HTTPS.
- Session token persists only in Windows Credential Manager. Browser-only development fallback uses sessionStorage with one-hour TTL.
- Profile/entitlement mirror uses sessionStorage. Local copies never override server authorization.
- PostgreSQL owns session, user, authorization-code, quota, credit, and webhook-derived billing state.

## Local startup

1. Website: apply supabase-auth-schema.sql and configure .env.local per DEV_SETUP.md.
2. Website: set BETTER_AUTH_URL and start npm run dev.
3. Desktop: copy .env.example to .env; set matching VITE_API_URL and VITE_GEMINI_MODEL.
4. Desktop: run npm run tauri:dev. Browser-only Vite mode cannot receive insertgo callback.
5. Sign in from Desktop, approve in system browser, then verify /api/auth/get-session and one streamed generation.

## Failure map

| Symptom | Check |
| --- | --- |
| Browser does not open | opener capability and copyable authorization URL |
| Login returns to wrong host or port | exact VITE_API_URL / BETTER_AUTH_URL origin match |
| Approval works but app never resumes | real Tauri build, insertgo scheme registration, deep-link and single-instance plugins |
| invalid_grant from token endpoint | expired/replayed code, wrong verifier, or interrupted sign-in attempt |
| Repeated 401 | expired/revoked bearer token or failed credential-store hydration |
| Packaged app network failure | Tauri HTTP capability allowlist and HTTPS certificate |
| 402 after generation request | server credit ledger; refresh account session |
| 503 from generation | Website database, quota gate, GEMINI_API_KEY, or upstream capacity |
| Checkout opens but plan stays old | Dodo webhook URL, secret, signature, event subscription, database update |

## Coordinated-change checklist

When changing connection contract:

1. Update server validation/response first, preserving backward compatibility when deployed Desktop clients exist.
2. Update Desktop consumer and friendly error mapping.
3. Update both .env.example files and DEV_SETUP.md when origin or required configuration changes.
4. Update Tauri capability allowlist when host changes.
5. Update tests: Desktop pkce.test.ts, http.test.ts, aiProviders.test.ts; Website desktopAuth.test.ts, entitlements.test.ts, usageLimit.test.ts, dodo.test.ts.
6. Update this template in scripts/sync-context.mjs; run npm run context:sync.
7. Test full real-app flow: browser approval, deep-link callback, token exchange, session refresh, SSE generation, credit update, logout.

## Standards and implementation references

- RFC 8252, OAuth 2.0 for Native Apps: https://www.rfc-editor.org/rfc/rfc8252
- RFC 7636, Proof Key for Code Exchange: https://www.rfc-editor.org/rfc/rfc7636
- RFC 9700, OAuth 2.0 Security Best Current Practice: https://www.rfc-editor.org/rfc/rfc9700
- Tauri v2 deep linking: https://v2.tauri.app/plugin/deep-linking/
- Better Auth bearer plugin: https://better-auth.com/docs/plugins/bearer
- Repository sources: Website DEV_SETUP.md and lib/desktopAuth.ts; Desktop src/store/authStore.ts and src-tauri/tauri.conf.json.
`;
}

async function atomicWrite(targetPath, content) {
  const normalized = `${content.trimEnd()}\n`;
  const current = (await exists(targetPath))
    ? await readFile(targetPath, "utf8")
    : null;
  if (current === normalized) return false;

  const temporaryPath = `${targetPath}.${process.pid}.tmp`;
  try {
    await writeFile(temporaryPath, normalized, "utf8");
    try {
      await rename(temporaryPath, targetPath);
    } catch (error) {
      if (!["EEXIST", "EPERM"].includes(error.code)) throw error;
      await copyFile(temporaryPath, targetPath);
    }
  } finally {
    await rm(temporaryPath, { force: true });
  }
  return true;
}

async function syncFiles(directory, targets, content) {
  if (!(await exists(directory))) {
    warnings.push(`missing project: ${directory}`);
    return [];
  }

  const changed = [];
  for (const name of targets) {
    const targetPath = path.join(directory, name);
    if (await atomicWrite(targetPath, content)) changed.push(targetPath);
  }
  return changed;
}

async function syncProject(directory, content, extraTargets = []) {
  return syncFiles(
    directory,
    [...canonicalTargets, ...extraTargets],
    content,
  );
}

const [desktopManifest, websiteManifest, rust] = await Promise.all([
  readJson(path.join(desktopDir, "package.json")),
  readJson(path.join(websiteDir, "package.json")),
  rustVersion(),
]);

const changed = [
  ...(await syncProject(
    desktopDir,
    desktopTemplate(desktopManifest, rust),
  )),
  ...(await syncProject(
    websiteDir,
    websiteTemplate(websiteManifest),
    websiteLegacyTargets,
  )),
  ...(await syncFiles(
    desktopDir,
    [integrationTarget],
    integrationTemplate(desktopManifest, websiteManifest, rust),
  )),
  ...(await syncFiles(
    websiteDir,
    [integrationTarget],
    integrationTemplate(desktopManifest, websiteManifest, rust),
  )),
];

for (const warning of warnings) console.warn(`sync-context: ${warning}`);
console.log(
  changed.length
    ? `sync-context: wrote ${changed.length} file(s)`
    : "sync-context: already clean",
);
